openApiPackageName: "com.databricks.partnerconnect"
openApiApiPackage: "com.databricks.partnerconnect.api"
openApiModelPackage: "com.databricks.partnerconnect.model"
openApiInvokerPackage: "com.databricks.partnerconnect.invoker"
generatorName: "scala-akka"
outputDir : "generated"
openApiGenerateApiTests: "true"
modelPropertyNaming: "original"
openApiGenerateApiDocumentation: "true"
openApiGenerateModelDocumentation: "true"